//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteAppNews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBloco
    {
        public int CodBloco { get; set; }
        public int CodTipoBloco { get; set; }
        public int CodAssociacao { get; set; }
        public string DescBloco { get; set; }
        public System.DateTime Data { get; set; }
        public int Ordem { get; set; }
    
        public virtual tblBlocoTipo tblBlocoTipo { get; set; }
    }
}
