//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteAppNews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNoticia
    {
        public int CodNoticia { get; set; }
        public int CodNoticiaTipo { get; set; }
        public string TituloNoticia { get; set; }
        public string DescNoticia { get; set; }
        public bool FlagAtivo { get; set; }
    
        public virtual tblNoticiaTipo tblNoticiaTipo { get; set; }
    }
}
