//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteAppNews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNoticiaImagem
    {
        public int CodNoticiaImagem { get; set; }
        public int CodNoticia { get; set; }
        public string CaminhoImagem { get; set; }
    }
}
