//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteAppNews.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyAppNewsEntities : DbContext
    {
        public EasyAppNewsEntities()
            : base("name=EasyAppNewsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblBloco> tblBloco { get; set; }
        public DbSet<tblBlocoTipo> tblBlocoTipo { get; set; }
        public DbSet<tblEnquete> tblEnquete { get; set; }
        public DbSet<tblEnqueteResposta> tblEnqueteResposta { get; set; }
        public DbSet<tblEnqueteRespostaUsuario> tblEnqueteRespostaUsuario { get; set; }
        public DbSet<tblEnqueteTipo> tblEnqueteTipo { get; set; }
        public DbSet<tblNoticia> tblNoticia { get; set; }
        public DbSet<tblNoticiaImagem> tblNoticiaImagem { get; set; }
        public DbSet<tblNoticiaTipo> tblNoticiaTipo { get; set; }
        public DbSet<tblResposta> tblResposta { get; set; }
    }
}
