//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsAppNews.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnqueteTipo
    {
        public tblEnqueteTipo()
        {
            this.tblEnquete = new HashSet<tblEnquete>();
        }
    
        public int CodEnqueteTipo { get; set; }
        public string DescEnqueteTipo { get; set; }
    
        public virtual ICollection<tblEnquete> tblEnquete { get; set; }
    }
}
