//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsAppNews.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNoticiaTipo
    {
        public tblNoticiaTipo()
        {
            this.tblNoticia = new HashSet<tblNoticia>();
        }
    
        public int CodNoticiaTipo { get; set; }
        public string DescNoticiaTipo { get; set; }
    
        public virtual ICollection<tblNoticia> tblNoticia { get; set; }
    }
}
