//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsAppNews.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTipoBloco
    {
        public tblTipoBloco()
        {
            this.tblBloco = new HashSet<tblBloco>();
        }
    
        public int CodTipoBLoco { get; set; }
        public string DescTipoBloco { get; set; }
    
        public virtual ICollection<tblBloco> tblBloco { get; set; }
    }
}
